version: '3.8'

services:
  router-high:
    build: .
    container_name: cisco-high
    environment:
      - DEVICE_PROFILE=high_utilized
      - DEVICE_HOSTNAME=r-high-1
      - DEVICE_VENDOR=cisco
      - DEVICE_MODEL=Catalyst 9000
      - DEVICE_PORT=8001
    ports:
      - 8001:8001

  router-low:
    build: .
    container_name: cisco-low
    environment:
      - DEVICE_PROFILE=low_utilized
      - DEVICE_HOSTNAME=r-low-1
      - DEVICE_VENDOR=cisco
      - DEVICE_MODEL=Catalys 9000x
      - DEVICE_PORT=8002
    ports:
      - "127.0.0.1:8002:8002"

  router-avg:
    build: .
    container_name: cisco-avg
    environment:
      - DEVICE_PROFILE=standard
      - DEVICE_HOSTNAME=r-avg-1
      - DEVICE_VENDOR=cisco
      - DEVICE_MODEL=Catalyst 8000
      - DEVICE_PORT=8003
    ports:
      - "127.0.0.1:8003:8003"

  juniper-avg:
    build: .
    container_name: juniper-avg
    environment:
      - DEVICE_PROFILE=standard
      - DEVICE_HOSTNAME=r-junos-avg-1
      - DEVICE_VENDOR=juniper
      - DEVICE_MODEL=ACX5400
      - DEVICE_PORT=8004
    ports:
      - "127.0.0.1:8004:8004"

  juniper-high:
    build: .
    container_name: juniper-high
    environment:
      - DEVICE_PROFILE=standard
      - DEVICE_HOSTNAME=r-junos-2
      - DEVICE_VENDOR=juniper
      - DEVICE_MODEL=EX4200
      - DEVICE_PORT=8005
    ports:
      - "127.0.0.1:8005:8005"

  juniper-low:
    build: .
    container_name: juniper-low
    environment:
      - DEVICE_PROFILE=low_utilzed
      - DEVICE_HOSTNAME=s-low-2
      - DEVICE_VENDOR=juniper
      - DEVICE_MODEL=EX400
      - DEVICE_PORT=8006
    ports:
      - "127.0.0.1:8006:8006"
  